adding ecotax to product variant
shoppingflux/php-feed-generator pull request #21
Opened 2022-08-19 13:05 UTC by bogdan202

allow to add the ecotax to a product variant in the module for PrestaShop

2022-08-19 16:15 UTC, clotairer approved these changes

2022-08-19 16:17 UTC, clotairer commented
Linked to this feature : 
https://github.com/shoppingflux/module-prestashop/pull/176

2022-09-12 10:29 UTC, budrea commented
The ecotax info is something only available at the product (parent) level. The variation (child) inherits this information. 

If we want to change this behaviour, we need to have a discussion at the Product level (at Shoppingfeed) and see what this implies. So I cannot validate this PR, for now. 

Thanks.

2022-12-02 14:11 UTC, budrea approved these changes
We're in the process of making the ecotax property available at the variation level, so we can now approve this PR. Thank you for the proposal. 

It will be released next week.

2022-12-02 15:02 UTC, william-leny requested changes

2022-12-02 15:02 UTC, william-leny commented on src/Xml/XmlProductFeedWriter.php
> +        if ($ecotax = $product->getEcotax()) {
there is an extraneous `ecotax` element in `writeProduct` method.
tested with `php tests/functional/products-random.php feed.xml 1` (set the ecotax to product in the script)

2022-12-06 10:42 UTC, budrea commented
I spoke too soon, we won't be supporting the ecotax property at the child / variation level just yet. So I'm closing the PR for now. 

Thanks again for the proposal. If we decide to support this, I'll revive it (or propose a new PR, re-using your code).

2022-12-06 10:42 UTC, closed without merging